name: mirrorchyan_release

on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        required: false

jobs:
  mirrorchyan:
    runs-on: macos-latest
    if: ${{ github.repository_owner == 'sunyink' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: win
            arch: x86_64
            filename: 'MFABD2-*-win-x86_64.zip'
          - os: win
            arch: aarch64
            filename: 'MFABD2-*-win-aarch64.zip'
          - os: macos
            arch: x86_64
            filename: 'MFABD2-*-macos-x86_64.zip'
          - os: macos
            arch: aarch64
            filename: 'MFABD2-*-macos-aarch64.zip'
          - os: linux
            arch: x86_64
            filename: 'MFABD2-*-linux-x86_64.zip'
          - os: linux
            arch: aarch64
            filename: 'MFABD2-*-linux-aarch64.zip'
          - os: android
            arch: aarch64
            filename: 'MFABD2-*-android-arm64.zip'

    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: ${{ matrix.filename }}
          mirrorchyan_rid: MFABD2
          tag: ${{ inputs.tag }}

          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

          owner: sunyink
          repo: MFABD2
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}

  # 热更新资源包：从全量包中抽取 resource + interface.json
  mirrorchyan_res:
    runs-on: macos-latest
    if: ${{ github.repository_owner == 'sunyink' }}
    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: 'MFABD2-*-win-x86_64.zip'
          pick_files: '["resource", "interface.json"]'
          # 截止3.1.0，MFAA有时对热更新，错误地进行全量更新操作，删除ocr并从希望热更新包寻找替代。暂时将ocr模型打包到热更新包中，避免用户反复重下全量包。
          # exclude_files: '["resource/model/ocr/**"]'

          mirrorchyan_rid: MFABD2
          tag: ${{ inputs.tag }}

          owner: sunyink
          repo: MFABD2
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
